# Generated by Django 3.1 on 2022-05-03 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_comprasenc_fecha1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasenc',
            name='fecha1',
        ),
    ]
