# Generated by Django 3.1 on 2022-05-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_comprasenc_fecha1'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadet',
            name='observaciones',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
