# Generated by Django 3.1 on 2022-05-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_facturadet_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturadet',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='observaciones',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
