# Generated by Django 3.1 on 2022-05-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220503_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaenc',
            name='complete_mant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='en_mantenimiento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='no_mantenimiento',
            field=models.BooleanField(default=True),
        ),
    ]
